# Generated by Django 4.2.6 on 2024-05-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_or_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
